spring.application.name=workhub
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/workhub
spring.datasource.username=workhub
spring.datasource.password=workhub
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.web.error.include-stacktrace=never